### PR TITLE
CMOS_CONTROL_B_CONFIG configurable from config.inc

### PR DESCRIPTION
**Pull request by spark2k06**
Useful to provide the user with the possibility to change the time format or DSE (Daylight Savings Enable)

### CODE REVIEW

**Comment by skiselev** [comment]
I've added daylight saving configuration in BIOS setup utility in this https://github.com/skiselev/8088_bios/commit/fb2fd1abb2c776c8be01b8ca00a9657238e89b25 commit.
I didn't have a chance to test it yet. If possible, please test.

**Comment by spark2k06** [comment]
Much better in the setup, yes :-)

A couple of things, the setup.inc is missing this part, otherwise it doesn't compile:

```
default_config_a db	00000000b	; NVRAM BIOS configuration byte A
;			||||||`---------; 00 = 4.77 MHz / Turbo off
;			|||||`----------; 0 = F0000-F7FFF ROM scan enabled
;			`---------------; reserved
nvram_trbo_mask equ	03h		; turbo mask
nvram_ext_scan	equ	04h		; F0000-F7FFF BIOS extension scan bit
					; (0 - enabled, 1 - disabled)
```


After of "RTC (Real Time Clock): ...", 0Dh + 0Ah is required, otherwise the DSE message appears together.


On the other hand, with these changes the speed change has stopped working ... the options '4', '7' and '9' are not recognized in the setup after pressing 'c' and is always at 4.77 Mhz the CPU.

Otherwise, the DSE option now works perfectly.

**Comment by skiselev** [comment]
I've actually already fixed that comment issue... Glad it is working.

**Comment by spark2k06** [comment]
I had not noticed the latest fixes, everything is perfect.

**Comment by skiselev** [comment]
I did yet another commit https://github.com/skiselev/8088_bios/commit/e200dbed8da0c13061398e695a46b8021d8a466a. It should fix the daylight saving display and also CPU frequency settings.

**Comment by spark2k06** [comment]
Ok

> I did yet another commit [e200dbe](https://github.com/skiselev/8088_bios/commit/e200dbed8da0c13061398e695a46b8021d8a466a). It should fix the daylight saving display and also CPU frequency settings.

I will try it. I see that you have also added "Scan F0000-F7FFF area for BIOS extension ROMs", great!

**Pull request closed without merging**
